### ISSUE TITLE
question - What am I doing wrong to not get to use this awesome component?

### ISSUE THREAD

**Issue by HippErger** [hew/react-scroll-horizontal#34]
###yarned all dependencies, followed readme exact and when I spin it up I get this error: 

####TypeError: _this4.props.children is not a function

react-scroll-horizontal.js:212 Uncaught TypeError: _this4.props.children is not a function
    at Object.children (react-scroll-horizontal.js:212)
    at Motion.render (Motion.js:255)
    at finishClassComponent (react-dom.development.js:13193)
    at updateClassComponent (react-dom.development.js:13155)
    at beginWork (react-dom.development.js:13824)
    at performUnitOfWork (react-dom.development.js:15863)
    at workLoop (react-dom.development.js:15902)
    at renderRoot (react-dom.development.js:15942)
    at performWorkOnRoot (react-dom.development.js:16560)
    at performWork (react-dom.development.js:16482)
    at performSyncWork (react-dom.development.js:16454)
    at requestWork (react-dom.development.js:16354)
    at scheduleWork$1 (react-dom.development.js:16218)
    at scheduleRootUpdate (react-dom.development.js:16785)
    at updateContainerAtExpirationTime (react-dom.development.js:16812)
    at updateContainer (react-dom.development.js:16839)
    at ReactRoot../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (react-dom.development.js:17122)
    at react-dom.development.js:17262
    at unbatchedUpdates (react-dom.development.js:16679)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:17258)
    at Object.render (react-dom.development.js:17317)
    at Object../src/index.js (index.js:8)
    at __webpack_require__ (bootstrap ee20e96b393a3ea4c35e:678)
    at fn (bootstrap ee20e96b393a3ea4c35e:88)
    at Object.0 (app.css?23b1:26)
    at __webpack_require__ (bootstrap ee20e96b393a3ea4c35e:678)
    at ./node_modules/ansi-regex/index.js.module.exports (bootstrap ee20e96b393a3ea4c35e:724)
    at bootstrap ee20e96b393a3ea4c35e:724

**Comment by hew** [comment]
@HippErger hmm, this looks like the same thing as https://github.com/hew/react-scroll-horizontal/issues/32, which I closed on @tailornirmal (sorry!). 

Gonna look into this today, so I should have an update later.

**Comment by hew** [comment]
You are doing nothing wrong. This was an error on my part. I've fixed it with this latest version: https://github.com/hew/react-scroll-horizontal/releases/tag/v1.5.0

**Comment by HippErger** [comment]
Thank you for looking into this. Not throwing an error anymore but still can't get it to render. I've put content in the empty divs, colored the background and still doesn't even show up in DevTools.

**Comment by hew** [comment]
Hmm - so to confirm, the component isn't mounting into the DOM?

Got a repo I can take a look at?

**Comment by ayanez17** [comment]
Same here, things are not rendering or mounting to the DOM. My code looks as follows:
```
      <div>
        <Message
          error
          hidden= {!this.state.failure}
          header='There was an error'
          content={this.state.errorMessage}
          onDismiss={()=>this.setState({failure:false})}
        />
        <Divider horizontal>
          Meetings
        </Divider>

        <HorizontalScroll>
          <p style = {child}></p>
        </HorizontalScroll>
      </div>
```

FYI:
`"react-scroll-horizontal": "^1.5.1"`

**Comment by hew** [comment]
> expected array

Which version of React are you using?
